/* Drop Tables */
DROP TABLE T_REPLY CASCADE CONSTRAINTS;
DROP TABLE T_BOARD CASCADE CONSTRAINTS;
DROP TABLE T_FRIEND CASCADE CONSTRAINTS;
DROP TABLE T_GREQUEST CASCADE CONSTRAINTS;
DROP TABLE T_PLIST CASCADE CONSTRAINTS;
DROP TABLE T_GROUP CASCADE CONSTRAINTS;
DROP TABLE T_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE T_SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE T_PLANNER CASCADE CONSTRAINTS;
DROP TABLE T_REQUEST CASCADE CONSTRAINTS;
DROP TABLE T_USER CASCADE CONSTRAINTS;


CREATE TABLE T_USER
(
   USERID varchar2(20) NOT NULL ,
   USERPWD varchar2(20) NOT NULL,
   USERNAME varchar2(20) NOT NULL,
   BIRTH date NOT NULL,
   PHONE varchar2(50) NOT NULL,
   EMAIL varchar2(50) NOT NULL,
   ORIGINALIMAGE varchar2(100),
   SAVEDIMAGE varchar2(100),
   INTRODUCE varchar2(1000),
   BELONG varchar2(50),
   PRIMARY KEY (USERID)
);

/* Create Tables */

CREATE TABLE T_BOARD
(
   BOANUM number NOT NULL,
   BOATITLE varchar2(100) NOT NULL,
   BOACONTENT varchar2(2000) NOT NULL,
   BOAREGDATE date DEFAULT SYSDATE,
   USERID varchar2(20) NOT NULL,
   GRONUM number NOT NULL,
   ORIGINALFILE varchar2(1000),
   SAVEDFILE varchar2(1000),
   PRIMARY KEY (BOANUM)
);


CREATE TABLE T_FRIEND
(
   FRINUM number NOT NULL,
   FRIREQUESTER varchar2(20) NOT NULL,
   FRIACCEPTER varchar2(20) NOT NULL,
   ISACCEPTED number(4) DEFAULT 0,
   PRIMARY KEY (FRINUM)
);


CREATE TABLE T_GREQUEST
(
   GREQNUM number NOT NULL,
   GREQUESTER varchar2(20) NOT NULL,
   GREQACCEPTER varchar2(20) NOT NULL,
   ISGREQACCEPTED number(4) DEFAULT 0,
   GRONUM number NOT NULL,
   PRIMARY KEY (GREQNUM)
);


CREATE TABLE T_GROUP
(
   GRONUM number NOT NULL,
   USERID varchar2(20) NOT NULL, 
   GRONAME varchar2(100) NOT NULL,
   GROINTRO varchar2(2000) NOT NULL,
   GROREGDATE date DEFAULT SYSDATE,
   USERCOUNT number DEFAULT 1,
   ORIGINALIMAGE varchar2(100),
   SAVEDIMAGE varchar2(100),
   PRIMARY KEY (GRONUM)
);


CREATE TABLE T_MESSAGE
(
   MESNUM number(20) NOT NULL,
   MESCONTEXT varchar2(100) NOT NULL,
   MESREGDATE date DEFAULT sysdate,
   USERA varchar2(20) NOT NULL,
   USERB varchar2(20) NOT NULL,
   PRIMARY KEY (MESNUM)
);


CREATE TABLE T_PLANNER
(
   PLANUM number NOT NULL,
   PLATITLE varchar2(20) NOT NULL,
   PLAREGDATE date DEFAULT sysdate NOT NULL,
   PRIMARY KEY (PLANUM)
);


CREATE TABLE T_PLIST
(
   PLNUM number NOT NULL ,
   PLANUM number NOT NULL,
   USERID varchar2(20) NOT NULL,
   PRIMARY KEY (PLNUM)
);


CREATE TABLE T_REPLY
(
   REPNUM number NOT NULL ,
   USERID varchar2(20) NOT NULL,
   REPTEXT varchar2(1000) NOT NULL,
   REPREGDATE date DEFAULT SYSDATE,
   BOANUM number NOT NULL,
   PRIMARY KEY (REPNUM)
);


CREATE TABLE T_REQUEST
(
   REQNUM number NOT NULL,
   REQUESTER varchar2(20) NOT NULL,
   REQACCEPTER varchar2(20) NOT NULL,
   ISACCEPTED number(4) DEFAULT 0,
   PLANUM number NOT NULL,
   PRIMARY KEY (REQNUM)
);


CREATE TABLE T_SCHEDULE
(
   SCHNUM number NOT NULL ,
   SCHTITLE varchar2(100) NOT NULL,
   SCHCONTENT varchar2(2000) NOT NULL,
   SCHREGDATE date DEFAULT SYSDATE,
   SCHSTARTDATE date NOT NULL,
   -- null?? ??? startdate?? ????
   SCHENDDATE date,
   IMPORTANCE varchar2(20) NOT NULL,
   CHECKED number DEFAULT 0 NOT NULL,
   SHAREABLE number DEFAULT 0 NOT NULL,
   PLANUM number NOT NULL,
   CATEGORY varchar2(20) NOT NULL,
   SCHLOCATION varchar2(50),
   PRIMARY KEY (SCHNUM)
);






/* Create Foreign Keys */

ALTER TABLE T_REPLY
   ADD FOREIGN KEY (BOANUM)
   REFERENCES T_BOARD (BOANUM)
;


ALTER TABLE T_BOARD
   ADD FOREIGN KEY (GRONUM)
   REFERENCES T_GROUP (GRONUM)
;


ALTER TABLE T_GREQUEST
   ADD FOREIGN KEY (GRONUM)
   REFERENCES T_GROUP (GRONUM)
;


ALTER TABLE T_PLIST
   ADD FOREIGN KEY (PLANUM)
   REFERENCES T_PLANNER (PLANUM)
;


ALTER TABLE T_SCHEDULE
   ADD FOREIGN KEY (PLANUM)
   REFERENCES T_PLANNER (PLANUM)
;


ALTER TABLE T_BOARD
   ADD FOREIGN KEY (USERID)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_FRIEND
   ADD FOREIGN KEY (FRIREQUESTER)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_FRIEND
   ADD FOREIGN KEY (FRIACCEPTER)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_GREQUEST
   ADD FOREIGN KEY (GREQUESTER)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_GREQUEST
   ADD FOREIGN KEY (GREQACCEPTER)
   REFERENCES T_USER (USERID)
;

ALTER TABLE T_GROUP
    ADD FOREIGN KEY (USERID)
    REFERENCES T_USER (USERID)
;

ALTER TABLE T_MESSAGE
   ADD FOREIGN KEY (USERA)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_MESSAGE
   ADD FOREIGN KEY (USERB)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_PLIST
   ADD FOREIGN KEY (USERID)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_REPLY
   ADD FOREIGN KEY (USERID)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_REQUEST
   ADD FOREIGN KEY (REQUESTER)
   REFERENCES T_USER (USERID)
;


ALTER TABLE T_REQUEST
   ADD FOREIGN KEY (REQACCEPTER)
   REFERENCES T_USER (USERID)
;

CREATE SEQUENCE T_USER_SEQ;
CREATE SEQUENCE T_PLIST_SEQ;
CREATE SEQUENCE T_PLANNER_SEQ;
CREATE SEQUENCE T_SCHEDULE_SEQ;
CREATE SEQUENCE T_GROUP_SEQ;
CREATE SEQUENCE T_REQUEST_SEQ;
CREATE SEQUENCE T_BOARD_SEQ;
CREATE SEQUENCE T_REPLY_SEQ;
CREATE SEQUENCE T_FRIEND_SEQ;
CREATE SEQUENCE T_MASSAGE_SEQ;

/* user insert */

commit
INSERT INTO T_USER (USERID, USERPWD, USERNAME, BIRTH, PHONE, EMAIL) VALUES ('admin', 'admin', 'admin', '1992-05-05', '010-0000-0000', 'admin@admin.net');
SELECT * FROM T_USER;
SELECT * FROM T_FRIEND;
SELECT * FROM T_PLANNER;


insert into T_SCHEDULE(
    SCHNUM,
    SCHTITLE,
    SCHCONTENT,
    SCHSTARTDATE,
    SCHENDDATE,
    IMPORTANCE,
    PLANUM,
   CATEGORY
    )VALUES(
    T_SCHEDULE_SEQ.NEXTVAL,
    '스케줄',
    'hghghghg',
    '2018.9.01',
    '2018.9.11',
    '3',
    41,
    '카테고리...'
    );
    insert into T_SCHEDULE(
    SCHNUM,
    SCHTITLE,
    SCHCONTENT,
    SCHSTARTDATE,
    SCHENDDATE,
    IMPORTANCE,
    PLANUM,
   CATEGORY
    )VALUES(
    T_SCHEDULE_SEQ.NEXTVAL,
    '두번째 스케줄',
    'ㅋㅋㅋ',
    '2018.9.01',
    '2018.9.11',
    '1',
    41,
    '카테고리2...'
    );
    insert into T_SCHEDULE(
    SCHNUM,
    SCHTITLE,
    SCHCONTENT,
    SCHSTARTDATE,
    SCHENDDATE,
    IMPORTANCE,
    PLANUM,
   CATEGORY
    )VALUES(
    T_SCHEDULE_SEQ.NEXTVAL,
    '세번째 스케줄',
    'ㅏㅏ',
    '2018.9.01',
    '2018.9.11',
    '2',
    1,
    '카테고리...'
    );
    insert into T_SCHEDULE(
    SCHNUM,
    SCHTITLE,
    SCHCONTENT,
    SCHSTARTDATE,
    SCHENDDATE,
    IMPORTANCE,
    PLANUM,
   CATEGORY
    )VALUES(
    T_SCHEDULE_SEQ.NEXTVAL,
    '네번째 스케줄',
    'dgffgㅏㅏ',
    '2018.9.01',
    '2018.9.11',
    '4',
    1,
    '카테고리...'
    );
    insert into T_SCHEDULE(
    SCHNUM,
    SCHTITLE,
    SCHCONTENT,
    SCHSTARTDATE,
    SCHENDDATE,
    IMPORTANCE,
    PLANUM,
   CATEGORY
    )VALUES(
    T_SCHEDULE_SEQ.NEXTVAL,
    '여섯번째 스케줄',
    'asdsdsaㅜㅠ',
    '2018.9.01',
    '2018.9.11',
    '1',
    6,
    '카테고리...'
    );
    
    insert into T_SCHEDULE(
    SCHNUM,
    SCHTITLE,
    SCHCONTENT,
    SCHSTARTDATE,
    SCHENDDATE,
    IMPORTANCE,
    PLANUM,
   CATEGORY
    )VALUES(
    T_SCHEDULE_SEQ.NEXTVAL,
    'osh첫번째 스케줄',
    'assaasㅏㅏㅏ',
    '2018.9.01',
    '2018.9.11',
    '2',
    4,
    '카테고리...'
    );
