
/* Drop Tables */

DROP TABLE T_REPLY CASCADE CONSTRAINTS;
DROP TABLE T_BOARD CASCADE CONSTRAINTS;
DROP TABLE T_FRIEND CASCADE CONSTRAINTS;
DROP TABLE T_GREQUEST CASCADE CONSTRAINTS;
DROP TABLE T_PLIST CASCADE CONSTRAINTS;
DROP TABLE T_GROUP CASCADE CONSTRAINTS;
DROP TABLE T_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE T_SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE T_PLANNER CASCADE CONSTRAINTS;
DROP TABLE T_REQUEST CASCADE CONSTRAINTS;
DROP TABLE T_USER CASCADE CONSTRAINTS;


CREATE TABLE T_USER
(
	USERID varchar2(20) NOT NULL ,
	USERPWD varchar2(20) NOT NULL,
	USERNAME varchar2(20) NOT NULL,
	BIRTH date NOT NULL,
	PHONE varchar2(50) NOT NULL,
	EMAIL varchar2(50) NOT NULL,
	IMAGE varchar2(100),
	INTRODUCE varchar2(1000),
	BELONG varchar2(50),
	PRIMARY KEY (USERID)
);

/* Create Tables */

CREATE TABLE T_BOARD
(
	BOANUM number NOT NULL,
	BOATITLE varchar2(100) NOT NULL,
	BOACONTENT varchar2(2000) NOT NULL,
	BOAREGDATE date DEFAULT SYSDATE,
	USERID varchar2(20) NOT NULL,
	GRONUM number NOT NULL,
	ORIGINALFILE varchar2(1000),
	SAVEDFILE varchar2(1000),
	PRIMARY KEY (BOANUM)
);


CREATE TABLE T_FRIEND
(
	FRINUM number NOT NULL,
	FRIREQUESTER varchar2(20) NOT NULL,
	FRIACCEPTER varchar2(20) NOT NULL,
	ISACCEPTED number(4) DEFAULT 0,
	PRIMARY KEY (FRINUM)
);


CREATE TABLE T_GREQUEST
(
	GREQNUM number NOT NULL,
	GREQUESTER varchar2(20) NOT NULL,
	GREQACCEPTER varchar2(20) NOT NULL,
	ISGREQACCEPTED number(4) DEFAULT 0,
	GRONUM number NOT NULL,
	PRIMARY KEY (GREQNUM)
);


CREATE TABLE T_GROUP
(
	GRONUM number NOT NULL,
	GRONAME varchar2(100) NOT NULL,
	GROINTRO varchar2(2000) NOT NULL,
	GROREGDATE date DEFAULT SYSDATE,
	USERCOUNT number DEFAULT 1,
	PRIMARY KEY (GRONUM)
);


CREATE TABLE T_MESSAGE
(
	MESNUM number(20) NOT NULL,
	MESCONTEXT varchar2(100) NOT NULL,
	MESREGDATE date DEFAULT sysdate,
	USERA varchar2(20) NOT NULL,
	USERB varchar2(20) NOT NULL,
	PRIMARY KEY (MESNUM)
);


CREATE TABLE T_PLANNER
(
	PLANUM number NOT NULL,
	PLATITLE varchar2(20) NOT NULL,
	PLAREGDATE date DEFAULT sysdate NOT NULL,
	PRIMARY KEY (PLANUM)
);


CREATE TABLE T_PLIST
(
	PLNUM number NOT NULL ,
	PLANUM number NOT NULL,
	GRONUM number,
	USERID varchar2(20) NOT NULL,
	PRIMARY KEY (PLNUM)
);


CREATE TABLE T_REPLY
(
	REPNUM number NOT NULL ,
	USERID varchar2(20) NOT NULL,
	REPTEXT varchar2(1000) NOT NULL,
	REPREGDATE date DEFAULT SYSDATE,
	BOANUM number NOT NULL,
	PRIMARY KEY (REPNUM)
);


CREATE TABLE T_REQUEST
(
	REQNUM number NOT NULL,
	REQUESTER varchar2(20) NOT NULL,
	REQACCEPTER varchar2(20) NOT NULL,
	ISACCEPTED number(4) DEFAULT 0,
	PLANUM number NOT NULL,
	PRIMARY KEY (REQNUM)
);


CREATE TABLE T_SCHEDULE
(
	SCHNUM number NOT NULL ,
	SCHTITLE varchar2(100) NOT NULL,
	SCHCONTENT varchar2(2000) NOT NULL,
	SCHREGDATE date DEFAULT SYSDATE,
	SCHSTARTDATE date NOT NULL,
	-- null�� ��� startdate�� ����
	SCHENDDATE date,
	IMPORTANCE varchar2(20) NOT NULL,
	CHECKED number DEFAULT 0 NOT NULL,
	SHAREABLE number DEFAULT 0 NOT NULL,
	PLANUM number NOT NULL,
	CATEGORY varchar2(20) NOT NULL,
	PRIMARY KEY (SCHNUM)
);






/* Create Foreign Keys */

ALTER TABLE T_REPLY
	ADD FOREIGN KEY (BOANUM)
	REFERENCES T_BOARD (BOANUM)
;


ALTER TABLE T_BOARD
	ADD FOREIGN KEY (GRONUM)
	REFERENCES T_GROUP (GRONUM)
;


ALTER TABLE T_GREQUEST
	ADD FOREIGN KEY (GRONUM)
	REFERENCES T_GROUP (GRONUM)
;


ALTER TABLE T_PLIST
	ADD FOREIGN KEY (GRONUM)
	REFERENCES T_GROUP (GRONUM)
;


ALTER TABLE T_PLIST
	ADD FOREIGN KEY (PLANUM)
	REFERENCES T_PLANNER (PLANUM)
;


ALTER TABLE T_SCHEDULE
	ADD FOREIGN KEY (PLANUM)
	REFERENCES T_PLANNER (PLANUM)
;


ALTER TABLE T_BOARD
	ADD FOREIGN KEY (USERID)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_FRIEND
	ADD FOREIGN KEY (FRIREQUESTER)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_FRIEND
	ADD FOREIGN KEY (FRIACCEPTER)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_GREQUEST
	ADD FOREIGN KEY (GREQUESTER)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_GREQUEST
	ADD FOREIGN KEY (GREQACCEPTER)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_MESSAGE
	ADD FOREIGN KEY (USERA)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_MESSAGE
	ADD FOREIGN KEY (USERB)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_PLIST
	ADD FOREIGN KEY (USERID)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_REPLY
	ADD FOREIGN KEY (USERID)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_REQUEST
	ADD FOREIGN KEY (REQUESTER)
	REFERENCES T_USER (USERID)
;


ALTER TABLE T_REQUEST
	ADD FOREIGN KEY (REQACCEPTER)
	REFERENCES T_USER (USERID)
;



/* Comments */

COMMENT ON COLUMN T_SCHEDULE.SCHENDDATE IS 'null�� ��� startdate�� ����';



